apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: cass-data-volume-0
spec:
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cass
  gcePersistentDisk:
    fsType: ext4
    pdName: pd-cass-testbed-disk-100g-0
---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: cass-data-volume-1
spec:
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cass
  gcePersistentDisk:
    fsType: ext4
    pdName: pd-cass-testbed-disk-100g-1

