# Default values for demoapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: vmturbo
  tag: 0.6
  locustTag: dev
  pullPolicy: IfNotPresent
  locustPullPolicy: Always
istioingress:
  enabled: true

locust:
  target_host: http://twitter-cass-api:8699
  max_twitter_user_id: 101
  max_num_follows: 50
  visit_rate_tweet: 100
  visit_rate_timeline: 100
  visit_rate_newsfeed: 1000
  visit_rate_follow: 10
  next_request_min_wait_ms: 1000
  next_request_max_wait_ms: 10000
  enable_time_slot_probality: 1
  time_slot_probability: 1.0,0.1
  time_slot_probability_step_in_min: 30
  locustfile: locustfile.py

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
   limits:
     cpu: 250m
     memory: 512Mi
   requests:
     cpu: 250m
     memory: 64Mi

cassandra:
  exporter:
    enabled: true
