apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: twitter-cass-api
  labels:
    app: twitter-cass-api
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: twitter-cass-api
    spec:
      containers:
      - name: twitter-cass-api
        image: {{ .Values.image.repository }}/twitter-cass-api:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8699
        resources:
{{ toYaml .Values.resources | indent 12 }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: twitter-cass-api
  labels:
    app: twitter-cass-api
spec:
  type: ClusterIP
  ports:
    - port: 8699
      name: http-twitter-cass-api
  selector:
    app: twitter-cass-api
---
